name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Set version
      run: |
        VERSION="${{ github.ref_name }}"
        VERSION="${VERSION#v}"
        yq -i ".settings.publishing.version = \"${VERSION}\"" module.yaml

    - name: Build
      run: ./kotlin build

    - name: Check
      run: ./kotlin check

    - name: Publish
      run: ./kotlin publish mavenCentral
      env:
        KOTLIN_TOOLCHAIN_MAVENCENTRAL_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
        KOTLIN_TOOLCHAIN_MAVENCENTRAL_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
        KOTLIN_TOOLCHAIN_SIGNING_KEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
        KOTLIN_TOOLCHAIN_SIGNING_KEY_PASSPHRASE: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
